fixed build issues: ./src/components/custom/video.tsx 43:34  Error: Unexpected empty arrow function.  @typescript-eslint/no-empty-function 61:16  Error: Unsafe assignment of an `any` value.  @typescript-eslint/no-unsafe-assignment
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/app/api-reference/config/eslint#disabling-rules
error: script "build" exited with code 1